
DROP TABLE IF EXISTS `#__post_tag`;
DROP TABLE IF EXISTS `#__post`;
DROP TABLE IF EXISTS `#__tag`;
DROP TABLE IF EXISTS `#__blog`;

CREATE TABLE `#__blog` (
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`title` VARCHAR(250) NOT NULL,
	`created_at` INT UNSIGNED NOT NULL
);

CREATE TABLE `#__post` (
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`blog_id` INT UNSIGNED NOT NULL,
	`title` VARCHAR(250) NOT NULL,
	`content` TEXT NOT NULL,
	`created_at` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`blog_id`) REFERENCES `#__blog` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `#__tag` (
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(250) NOT NULL
);

CREATE UNIQUE INDEX `#__tag_name` ON `#__tag` (`name`);

CREATE TABLE `#__post_tag` (
	`post_id` INT UNSIGNED NOT NULL,
	`tag_id` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`post_id`, `tag_id`),
	FOREIGN KEY (`post_id`) REFERENCES `#__post` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (`tag_id`) REFERENCES `#__tag` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
);
